version: '2'
services:
  seed:
    image: pako/akka-cluster
    environment:
      CLUSTER_PORT: 9090
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
  c1:
    image: pako/akka-cluster
    environment:
      CLUSTER_IP: c1
      CLUSTER_PORT: 9091
      SEED_PORT_1600_TCP_ADDR: seed
  c2:
    image: pako/akka-cluster
    environment:
      CLUSTER_IP: c2
      CLUSTER_PORT: 9091
      SEED_PORT_1600_TCP_ADDR: seed
  c3:
    image: pako/akka-cluster
    environment:
      CLUSTER_IP: c3
      CLUSTER_PORT: 9091
      SEED_PORT_1600_TCP_ADDR: seed
